#############################################################################
# Makefile for building: battleship3d
# Generated by qmake (1.05a) (Qt 3.1.2) on: Mon Jul 21 23:22:08 2003
# Project:  battleship3d.pro
# Template: app
# Command: $(QMAKE) -o Makefile battleship3d.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I$(QTDIR)/mkspecs/default -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS)  -Wl,-rpath,$(QTDIR)/lib -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lGL -lGLU
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY) -p
COPY_DIR = $(COPY) -pR
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = 3ds.h \
		3dsModel.h \
		bateau.h \
		camera.h \
		cartenavale.h \
		case.h \
		classetext.h \
		graphique.h \
		headers.h \
		mer.h \
		model.h \
		objet.h \
		PD.h \
		principale.h \
		skydome.h \
		terrain.h \
		texture.h \
		transf.h \
		tree.h
SOURCES = 3ds.cpp \
		bateau.C \
		camera.C \
		cartenavale.C \
		case.C \
		classetext.C \
		fonctions.C \
		graphique.C \
		mer.C \
		model.C \
		PD.cpp \
		principale.C \
		projet.C \
		skydome.C \
		terrain.C \
		texture.C \
		transf.C \
		tree.C
OBJECTS = 3ds.o \
		bateau.o \
		camera.o \
		cartenavale.o \
		case.o \
		classetext.o \
		fonctions.o \
		graphique.o \
		mer.o \
		model.o \
		PD.o \
		principale.o \
		projet.o \
		skydome.o \
		terrain.o \
		texture.o \
		transf.o \
		tree.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_graphique.cpp \
		moc_PD.cpp \
		moc_principale.cpp
OBJMOC = moc_graphique.o \
		moc_PD.o \
		moc_principale.o
DIST	   = battleship3d.pro
QMAKE_TARGET = battleship3d
DESTDIR  = 
TARGET   = battleship3d

first: all
####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

mocables: $(SRCMOC)

$(MOC): 
	( cd $(QTDIR)/src/moc ; $(MAKE) )

Makefile: battleship3d.pro  $(QTDIR)/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile battleship3d.pro
qmake: 
	@$(QMAKE) -o Makefile battleship3d.pro

dist: 
	@mkdir -p .tmp/battleship3d && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/battleship3d/ && ( cd `dirname .tmp/battleship3d` && $(TAR) battleship3d.tar battleship3d && $(GZIP) battleship3d.tar ) && $(MOVE) `dirname .tmp/battleship3d`/battleship3d.tar.gz . && $(DEL_FILE) -r .tmp/battleship3d

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS) 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

3ds.o: 3ds.cpp headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

bateau.o: bateau.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

camera.o: camera.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

cartenavale.o: cartenavale.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

case.o: case.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

classetext.o: classetext.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

fonctions.o: fonctions.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

graphique.o: graphique.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

mer.o: mer.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

model.o: model.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

PD.o: PD.cpp headers.h \
		images/icon1.xpm \
		images/icon2.xpm \
		images/icon3.xpm \
		images/icon4.xpm \
		images/icon5.xpm \
		images/cam1.xpm \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

principale.o: principale.C headers.h \
		images/filesave.xpm \
		images/fileopen.xpm \
		images/file_new.xpm \
		images/icon1.xpm \
		images/icon2.xpm \
		images/icon3.xpm \
		images/icon4.xpm \
		images/icon5.xpm \
		images/x.xpm \
		images/prop.xpm \
		images/cam1.xpm \
		images/cam2.xpm \
		images/cam3.xpm \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

projet.o: projet.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

skydome.o: skydome.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

terrain.o: terrain.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

texture.o: texture.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

transf.o: transf.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

tree.o: tree.C headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

moc_graphique.o: moc_graphique.cpp graphique.h headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

moc_PD.o: moc_PD.cpp PD.h headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

moc_principale.o: moc_principale.cpp principale.h headers.h \
		config \
		Francais.lng \
		English.lng \
		principale.h \
		transf.h \
		3dsModel.h \
		camera.h \
		texture.h \
		classetext.h \
		mer.h \
		cartenavale.h \
		objet.h \
		bateau.h \
		case.h \
		skydome.h \
		terrain.h \
		3ds.h \
		model.h \
		graphique.h \
		tree.h \
		PD.h

moc_graphique.cpp: $(MOC) graphique.h
	$(MOC) graphique.h -o moc_graphique.cpp

moc_PD.cpp: $(MOC) PD.h
	$(MOC) PD.h -o moc_PD.cpp

moc_principale.cpp: $(MOC) principale.h
	$(MOC) principale.h -o moc_principale.cpp

####### Install

install: all 

uninstall: 

